name: Create new Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'composer.json'
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: Create Changelog and bump release version
        uses: labor-digital/conventional-release-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}